# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Vivado_works/Second_Term/FPGA/FPGA.srcs/sources_1/ip/Jay/Jay.xci
# IP: The module: 'Jay' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Vivado_works/Second_Term/FPGA/FPGA.srcs/sources_1/ip/Jay/Jay_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Jay'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Vivado_works/Second_Term/FPGA/FPGA.srcs/sources_1/ip/Jay/Jay.xci
# IP: The module: 'Jay' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Vivado_works/Second_Term/FPGA/FPGA.srcs/sources_1/ip/Jay/Jay_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Jay'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
