# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/_SamData/Vivado2022/Codes/VGA/VGA.srcs/sources_1/ip/Clk25MHz/Clk25MHz.xci
# IP: The module: 'Clk25MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/_SamData/Vivado2022/Codes/VGA/VGA.srcs/sources_1/ip/Clk25MHz/Clk25MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clk25MHz'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/_SamData/Vivado2022/Codes/VGA/VGA.srcs/sources_1/ip/Clk25MHz/Clk25MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clk25MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/_SamData/Vivado2022/Codes/VGA/VGA.srcs/sources_1/ip/Clk25MHz/Clk25MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clk25MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/_SamData/Vivado2022/Codes/VGA/VGA.srcs/sources_1/ip/Clk25MHz/Clk25MHz.xci
# IP: The module: 'Clk25MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/_SamData/Vivado2022/Codes/VGA/VGA.srcs/sources_1/ip/Clk25MHz/Clk25MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clk25MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/_SamData/Vivado2022/Codes/VGA/VGA.srcs/sources_1/ip/Clk25MHz/Clk25MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clk25MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/_SamData/Vivado2022/Codes/VGA/VGA.srcs/sources_1/ip/Clk25MHz/Clk25MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Clk25MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
