# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Vivado_works/Second_Term/PCC_CPU/PCC_CPU.cache/wt [current_project]
set_property parent.project_path C:/Vivado_works/Second_Term/PCC_CPU/PCC_CPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Vivado_works/Second_Term/PCC_CPU/PCC_CPU.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  C:/Vivado_works/Second_Term/PCC_CPU/PCC_CPU.srcs/sources_1/imports/sources_1/new/DataMemoryDecoder.sv
  C:/Vivado_works/Second_Term/PCC_CPU/PCC_CPU.srcs/sources_1/imports/sources_1/imports/new/Hex7Seg.sv
  C:/Vivado_works/Second_Term/PCC_CPU/PCC_CPU.srcs/sources_1/imports/sources_1/new/IO.sv
  C:/Vivado_works/Second_Term/PCC_CPU/PCC_CPU.srcs/sources_1/imports/sources_1/imports/new/adder.sv
  C:/Vivado_works/Second_Term/PCC_CPU/PCC_CPU.srcs/sources_1/imports/sources_1/imports/new/alu.sv
  C:/Vivado_works/Second_Term/PCC_CPU/PCC_CPU.srcs/sources_1/imports/sources_1/imports/new/aludec.sv
  C:/Vivado_works/Second_Term/PCC_CPU/PCC_CPU.srcs/sources_1/imports/sources_1/imports/new/controller.sv
  C:/Vivado_works/Second_Term/PCC_CPU/PCC_CPU.srcs/sources_1/imports/sources_1/imports/new/datapath.sv
  C:/Vivado_works/Second_Term/PCC_CPU/PCC_CPU.srcs/sources_1/imports/sources_1/imports/new/dmem.sv
  C:/Vivado_works/Second_Term/PCC_CPU/PCC_CPU.srcs/sources_1/new/eqcmp.sv
  C:/Vivado_works/Second_Term/PCC_CPU/PCC_CPU.srcs/sources_1/imports/sources_1/new/flopenr.sv
  C:/Vivado_works/Second_Term/PCC_CPU/PCC_CPU.srcs/sources_1/new/flopenrc.sv
  C:/Vivado_works/Second_Term/PCC_CPU/PCC_CPU.srcs/sources_1/imports/sources_1/imports/new/flopr.sv
  C:/Vivado_works/Second_Term/PCC_CPU/PCC_CPU.srcs/sources_1/new/floprc.sv
  C:/Vivado_works/Second_Term/PCC_CPU/PCC_CPU.srcs/sources_1/new/hazard.sv
  C:/Vivado_works/Second_Term/PCC_CPU/PCC_CPU.srcs/sources_1/imports/sources_1/imports/new/imem.sv
  C:/Vivado_works/Second_Term/PCC_CPU/PCC_CPU.srcs/sources_1/imports/sources_1/imports/new/maindec.sv
  C:/Vivado_works/Second_Term/PCC_CPU/PCC_CPU.srcs/sources_1/imports/sources_1/imports/new/mips.sv
  C:/Vivado_works/Second_Term/PCC_CPU/PCC_CPU.srcs/sources_1/imports/sources_1/imports/new/mux2.sv
  C:/Vivado_works/Second_Term/PCC_CPU/PCC_CPU.srcs/sources_1/new/mux3.sv
  C:/Vivado_works/Second_Term/PCC_CPU/PCC_CPU.srcs/sources_1/imports/sources_1/imports/new/regfile.sv
  C:/Vivado_works/Second_Term/PCC_CPU/PCC_CPU.srcs/sources_1/imports/sources_1/imports/new/signext.sv
  C:/Vivado_works/Second_Term/PCC_CPU/PCC_CPU.srcs/sources_1/imports/sources_1/imports/new/sl2.sv
  C:/Vivado_works/Second_Term/PCC_CPU/PCC_CPU.srcs/sources_1/imports/sources_1/imports/new/x7seg.sv
  C:/Vivado_works/Second_Term/PCC_CPU/PCC_CPU.srcs/sources_1/imports/new/zeroext.sv
  C:/Vivado_works/Second_Term/PCC_CPU/PCC_CPU.srcs/sources_1/imports/sources_1/new/topext.sv
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Vivado_works/Second_Term/PCC_CPU/PCC_CPU.srcs/constrs_1/imports/PCC_CPU/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files C:/Vivado_works/Second_Term/PCC_CPU/PCC_CPU.srcs/constrs_1/imports/PCC_CPU/Nexys4DDR_Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top topext -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef topext.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file topext_utilization_synth.rpt -pb topext_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
